server:
   port: 8080

spring:
    jpa:
      hibernate:
        ddl-auto: update
        
    datasource:
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect
      url: jdbc:h2:mem:filme
      driver-class-name: org.h2.Driver
      username: sa
      password: sa 
      
    h2:
      console.enabled: true

    application: 
      name: filme
